### ISSUE TITLE
when setup api server use url from persistence instead of hard coded

### ISSUE THREAD

**Issue by ironmanwaring** [sweetskills/cloud-formation#145]
right now we have a hard coded string for part of the url path that is region-specific

**Comment by paulSambolin** [comment]
I am getting a circular dependency error between api and persistence.  API needs db address and DB needs API security group.  Would you want me to move the Security group from api to persistence and pass the group id back to api along with the DB endpoint?

**Comment by ironmanwaring** [comment]
do we have anything else security related that would warrant creating a new template just for that?

**Comment by paulSambolin** [comment]
There is also a db security group in persistence template.  I already moved the one security group to persistence so they are both in there on pull #146
